// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { ExtendedDatabase } from './extended-types';

// Forced credentials to match the correct project (ogtspcygnwxkpqmmlwzm)
const SUPABASE_URL = "https://ogtspcygnwxkpqmmlwzm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_S1qjlXeJiupqYuh7JVp56w_sh3hjuE7";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<ExtendedDatabase>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});